/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gdc_libxmlandroid_LibManager */

#ifndef _Included_com_gdc_libxmlandroid_LibManager
#define _Included_com_gdc_libxmlandroid_LibManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gdc_libxmlandroid_LibManager
 * Method:    test
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gdc_libxmlandroid_LibManager_test
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
